---
- name: Setup cockpit
  block:
  - name: Install cockpit
    ansible.builtin.apt:
      default_release: focal-backports
      name: cockpit=260-1~bpo20.04.1
      state: present

  - name: Create folder for cockpit
    ansible.builtin.file:
      state: directory
      path: /etc/cockpit
      owner: root

  - name: Create folder for cockpit certs
    ansible.builtin.file:
      state: directory
      path: /etc/cockpit/ws-certs.d
      owner: root

  - name: Copy cockpit config
    ansible.builtin.template:
      src: cockpit.conf
      dest: /etc/cockpit/cockpit.conf

  - name: Create logger user with password
    ansible.builtin.user:
      group: systemd-journal
      comment: This user should be used only for cockpit login
      create_home: no
      name: log-reader
      password: $1$IP7Smfew$S2E8pM1C.JCRjRaTnNeaW/

  - name: Enable cockpit service
    ansible.builtin.systemd:
      enabled: true
      name: cockpit.service

  - name: Restart cockpit service
    ansible.builtin.systemd:
      state: restarted
      name: cockpit.service

  # - name: Download cockpit release 260
  #   ansible.builtin.get_url:
  #     dest: ~/cockpit-260.tar.xz
  #     force: no
  #     url: https://github.com/cockpit-project/cockpit/releases/download/260/cockpit-260.tar.xz
  #     checksum: sha1:fb630c81745b08db09c1fd41f86d6b5f754bc4fc
  # - name: Create folder for cockpit build
  #   ansible.builtin.file:
  #     state: directory
  #     path: ~/cockpit-unpacked

  # - name: Unpack cockpit
  #   ansible.builtin.unarchive:
  #     remote_src: true
  #     dest: ~/cockpit-unpacked
  #     mode: u+rwx
  #     src: ~/cockpit-260.tar.xz
  # - name: install compiler
  #   ansible.builtin.apt:
  #     default_release: focal-backports
  #     name: cockpit=260-1~bpo20.04.1
  #     state: present
  #         # - gcc
  #         # - pkg-config
  #         # - libglib2.0-dev
  #         # - libsystemd-dev
  #         #   ibjson-glib-dev 
  #         #   json-glib-tools # Might not be necessary
  #         #   gnutls-bin
  #         #   libgnutls28-dev
