---
- name: Setup cockpit
  become: yes
  become_user: root
  block:

  - name: Include nginx
    import_tasks: nginx.yml
    tags: nginx

  - name: Include Cockpit
    import_tasks: cockpit.yml
    tags: cockpit


