---
- name: Setup nginx
  block:
    - name: Install nginx
      tags: nginx
      ansible.builtin.apt:
        name: nginx

    - name: Copy nginx config
      ansible.builtin.template:
        src: nginx_cockpit.conf
        dest: /etc/nginx/sites-available/cockpit.conf

    - name: Enable nginx cockpit config
      ansible.builtin.file:
        state: link
        src: /etc/nginx/sites-available/cockpit.conf
        dest: /etc/nginx/sites-enabled/default

    - name: Create folder for certificates
      ansible.builtin.file:
        state: directory
        path: "{{ certdir_path }}"
        mode: 0600

    - name: Copy public cert
      ansible.builtin.copy:
        dest: "{{ cert_path }}"
        mode: 0400
        src: domain.cert.pem
    

    - name: Copy public cert
      ansible.builtin.copy:
        dest: "{{ certkey_path }}"
        mode: 0400
        src: private.key.pem

    - name: Enable nginx service
      ansible.builtin.systemd:
        enabled: true
        name: nginx.service

    - name: Restart nginx service
      ansible.builtin.systemd:
        state: restarted
        name: nginx.service

