apiVersion: v1
kind: Service
metadata:
  name: vmservice-service
  namespace: apc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "VmSubnet"
spec:
  type: LoadBalancer
  loadBalancerIP:  {{ required "No lb ip specified" .Values.LBinternal }}
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: vmservice
