apiVersion: apps/v1
kind: Deployment
metadata:
  name: apc-vm-service-deployment
  namespace: apc
  labels:
    app: vmservice
    category: frontend
spec:
  selector:
    matchLabels:
      app: vmservice
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vmservice
        category: backend
    spec:
      imagePullSecrets:
        - name: container-registry
      containers:
        - name: vm-test-server
          image:
            {{- required "Docker repo required" .Values.dockerRepository | indent 1 -}}
             /services/vm-test-server:
            {{- .Values.releaseLabel }}
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          env:
            - name: RABBIT_MQ
              value: rabbitmq-cluster.apc
            - name: VM_TEST_ADDR
              valueFrom:
                secretKeyRef:
                  key: testVmAddress
                  name: general-secrets
            - name: VM_TEST_RETURN_ADDR
              value: {{ required "No lb ip specified" .Values.LBinternal }}:80
            - name: RESULTS_QUEUE_NAME
              value: {{ required "Test output queue missing" .Values.testResultsQueue }}
            - name: RESULTS_BLOB_CONN_STR
              valueFrom:
                secretKeyRef:
                  key: blobConnectionString
                  name: general-secrets
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 500Mi
              cpu: 500m