apiVersion: apps/v1
kind: Deployment
metadata:
  name: apc-presentation
  namespace: apc
  labels:
    app: presentation
    category: frontend
spec:
  selector:
    matchLabels:
      app: presentation
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: presentation
        category: frontend
    spec:
      containers:
        - name: presentation-pod
          image:
            {{- required "Docker repo required" .Values.dockerRepository | indent 1 -}}
             /services/presentation:
            {{- .Values.releaseLabel }}
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: 256M
              cpu: 100m
            limits:
              memory: 1G
              cpu: 500m
          env:
            - name: GoogleOid__ClientId
              valueFrom:
                secretKeyRef:
                  key: googleId
                  name: general-secrets
            - name: GoogleOid__ClientSecret
              valueFrom:
                secretKeyRef:
                  key: googleSecret
                  name: general-secrets
            - name: API_GATEWAY
              value: http://gateway-service.apc
            - name: STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  key: blobConnectionString
                  name: general-secrets
            - name: LINKS_CURRENT_DOCS
              value: https://cppseminar.atlassian.net/wiki/spaces/APC2022/overview
