apiVersion: v1
kind: Service
metadata:
  name: vmservice-service
  namespace: apc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-ipv4: {{ required "No lb ip specified" .Values.LBinternal }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: vmservice
