---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  namespace: apc
  name: mongodb
spec:
  members: 2
  arbiters: 1
  type: ReplicaSet
  version: "5.0.12"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
  - name: admin
    db: admin
    passwordSecretRef: 
      name: mongo-password
    roles:
    - name: root
      db: admin
    scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
