apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-db-backup
  namespace: apc
spec:
  schedule: "0 3,12 * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: container-registry
          containers:
          - name: mongo-db-backup
            image: 
            {{- required "Docker repo required" .Values.dockerRepository | indent 1 -}}
             /services/mongo-backup:
            {{- .Values.releaseLabel }}
            imagePullPolicy: Always
            env:
            - name: MONGO_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: mongodb-admin-admin
                  key: connectionString.standardSrv
                  optional: false
            - name: DUMPS_BLOB_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: general-secrets
                  key: blobConnectionString
                  optional: false
          restartPolicy: OnFailure