build: off
environment:
        matrix:
                - PYTHON: "C:\\Python36"
                - PYTHON: "C:\\Python37"
init:
        - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
install:
        - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
        - powershell /C ".\make.ps1 -python_path '%PYTHON%\\python.exe' -install"

test_script:
        - powershell /C ".\make.ps1 -python_path '%PYTHON%\\python.exe' -test"
