---
- name: Persist iptables-nft ipv4 across restarts
  become: yes
  become_user: root
  block:
    - name: Set iptables-nft as default iptables
      ansible.builtin.command:
        argv:
          - /usr/bin/update-alternatives
          - --set
          - iptables
          - /usr/sbin/iptables-nft

    - name: Create iptables directory
      ansible.builtin.file:
        mode: 0644
        path: /etc/iptables-nft4/
        state: directory

    - name: Copy bash script
      ansible.builtin.template:
        src: iptables-nft4-up.sh
        dest: /usr/local/sbin/iptables-nft4-up.sh
        mode: 0744

    - name: Copy systemd unit
      ansible.builtin.template:
        src: iptables-nft4.service
        dest: /etc/systemd/system/iptables-nft4.service

    - name: Autostart iptables
      ansible.builtin.systemd:
        name: iptables-nft4
        state: restarted
        enabled: true
