version: "3.8"
services:
    queue:
        container_name: queue1
        build:
            context: ./queue
            network: host
        init: true
        # restart_policy:
        #     condition: any
        #     delay: 5s
        #     max_attempts: 3
        #     window: 10s
        restart: always
        logging:
            driver: json-file
            options:
                max-size: "200k"
                max-file: "10"

        volumes:
            -  /var/run/docker.sock:/var/run/docker.sock

    input-proxy:
        env_file: .env
        ports:
            - 10017:10017
        build:
            context: ./input-proxy
            network: host
        logging:
            driver: json-file
            options:
                max-size: "200k"
                max-file: "10"

    output-proxy:
        env_file: .env
        build:
            context: ./output-proxy
            network: host
        logging:
            driver: json-file
            options:
                max-size: "200k"
                max-file: "10"
