---
- name: Setup logstash&cockpit server
  hosts: logger
  become: yes
  remote_user: root
  tasks:
    - name: Deploy logstash
      ansible.builtin.include_role:
        name: logstash

    - name: Deploy cockpit
      ansible.builtin.include_role:
        name: cockpit
