---
- name: Setup logstash&cockpit server
  hosts: server
  gather_facts: false
  become: yes
  remote_user: root
  tasks:
    - name: Deploy logstash
      tags: logstash
      ansible.builtin.include_role:
        name: logstash

    - name: Deploy cockpit
      ansible.builtin.include_role:
        name: cockpit
      tags: cockpit


