# This are working test requests to our function api. They of course
# work only if you have functions running locally.
@baseUrl = http://localhost:3000

GET {{baseUrl}}/api/submissions/ HTTP/1.1
Accept: */*
X-request-email: miro@example.net

####
GET {{baseUrl}}/api/submissions?user=miro@example.com HTTP/1.1
Accept: */*
X-request-email: miro@example.com

####

GET {{baseUrl}}/api/submissions/5f34fa499cd6ee86b5fe4370 HTTP/1.1
Accept: */*
X-request-email: miro@example.com

####
GET {{baseUrl}}/api/submissions?offset=5&limit=2 HTTP/1.1
Accept: */*
X-request-email: miro@example.net

####

POST {{baseUrl}}/api/submissions/ HTTP/1.1
Accept: */*
X-request-email: miro@example.com

{
        "files": [
                {
                        "fileContent": "import json\n print()",
                        "fileName" : "source.cpp"
                }
        ],
        "taskId": "5f3944f1bf1bb81e48bae8fa"
}


###########################
# tasks api
###########################
GET {{baseUrl}}/api/tasks?user=miro@example.com HTTP/1.1
Accept: */*
X-request-email: miro@example.com

##### Jozo is admin
GET {{baseUrl}}/api/tasks HTTP/1.1
Accept: */*
X-request-email: jozo@example.com

####
GET {{baseUrl}}/api/tasks/5f3944f1bf1bb81e48bae8fa HTTP/1.1
Accept: */*
X-request-email: miro@example.com
