# This are working test requests to our function api. They of course
# work only if you have functions running locally.
@baseUrl = http://localhost:3000

GET {{baseUrl}}/api/submissions/ HTTP/1.1
Accept: */*
X-request-email: miro@example.net

####
GET {{baseUrl}}/api/submissions/ HTTP/1.1
Accept: */*
X-request-email: jozo@example.com

####
GET {{baseUrl}}/api/submissions/5f3172e94ccb2b29ecbf28e0 HTTP/1.1
Accept: */*
X-request-email: jozo@example.com

####
GET {{baseUrl}}/api/submissions?offset=5&limit=2 HTTP/1.1
Accept: */*
X-request-email: miro@example.net

####

POST {{baseUrl}}/api/submissions/ HTTP/1.1
Accept: */*
X-request-email: jozo@example.com

{
        "files": [
                {
                        "fileContent":"#include",
                        "fileName" : "source.cpp"
                }
        ],
        "taskId": "5f3172e94ccb2b29ecbf28e0"
}
