# This are working test requests to our function api. They of course
# work only if you have functions running locally.
@baseUrl = http://localhost:3000
@user = miro@example.com
@admin = jozo@example.com

GET {{baseUrl}}/api/submissions/ HTTP/1.1
Accept: */*
X-request-email: miro@example.net

####
GET {{baseUrl}}/api/submissions?user=miro@example.com HTTP/1.1
Accept: */*
X-request-email: miro@example.com

####
GET {{baseUrl}}/api/submissions?user=miro@example.com&task=5f3944f1bf1bb81e48bae8fa  HTTP/1.1
Accept: */*
X-request-email: miro@example.com

####

GET {{baseUrl}}/api/submissions/5f50ac375cd93b87048013ef HTTP/1.1
Accept: */*
X-request-email: miro@example.com

####
GET {{baseUrl}}/api/submissions?offset=5&limit=2 HTTP/1.1
Accept: */*
X-request-email: miro@example.net

####

POST {{baseUrl}}/api/submissions/ HTTP/1.1
Accept: */*
X-request-email: miro@example.com

{
        "files": [
                {
                        "fileContent": "import json\n print()",
                        "fileName" : "source.cpp"
                }
        ],
        "taskId": "5f3944f1bf1bb81e48bae8fa"
}


###########################
# tasks api
###########################
GET {{baseUrl}}/api/tasks?user=miro@example.com HTTP/1.1
Accept: */*
X-request-email: miro@example.com

##### Jozo is admin
GET {{baseUrl}}/api/tasks HTTP/1.1
Accept: */*
X-request-email: {{admin}}

####
GET {{baseUrl}}/api/tasks?user=miro@example.com HTTP/1.1
Accept: */*
X-request-email: {{admin}}

####
GET {{baseUrl}}/api/tasks/5f3944f1bf1bb81e48bae8fa HTTP/1.1
Accept: */*
X-request-email: miro@example.com

##############################
# Test cases api
##############################
GET {{baseUrl}}/api/cases/5f3e8f187e296d1539d94845 HTTP/1.1
Accept: */*
X-request-email: {{user}}

###

GET {{baseUrl}}/api/cases/ HTTP/1.1
Accept: */*
X-request-email: {{user}}

###############################
# Tests api
###############################
POST {{baseUrl}}/api/tests/ HTTP/1.1
Accept: */*
X-request-email: {{user}}

{
        "submissionId":"5f50ac375cd93b87048013ef",
        "testCaseId": "5f3e8f187e296d1539d94845"
}

####

PATCH {{baseUrl}}/api/tests/5f57bf1d7cd144db25c05fd7
Accept: */*

{
        "description": "abcdef\n[ok] test ruw"
}

#####
GET {{baseUrl}}/api/users/ HTTP/1.1
Accept: */*
X-request-email: {{admin}}

#########################################
# Download submissions
#########################################
GET {{baseUrl}}/api/download/submissions/5f3944f1bf1bb81e48bae8fa
Accept: */*
X-request-email: {{admin}}
