apiVersion: v1
kind: Secret
metadata:
  namespace: apc
  name: general-secrets
type: Opaque
stringData:
  cosmosConnectionString: <redacted>
  blobConnectionString: <redacted>
  usersTableConnectionString: <redacted>
  googleId: <redacted>
  googleSecret: <redacted>
  testVmAddress: <redacted>
  testResponseAddress: <redacted>
  logstashHost: <redacted>

---
apiVersion: v1
kind: Secret
metadata:
  namespace: apc
  name: https-certs
type: kubernetes.io/tls
stringData:
  tls.crt: |
        -----BEGIN CERTIFICATE-----
        <redacted>
        -----END CERTIFICATE-----
  tls.key: |
        -----BEGIN PRIVATE KEY-----
        <redacted>
        -----END PRIVATE KEY-----
