apiVersion: v1
kind: Secret
metadata:
  namespace: apc
  name: general-secrets
type: Opaque
stringData:
  blobConnectionString: <redacted>
  blobAccountName: <redacted>
  blobAccountKey: <redacted>
  googleId: <redacted>
  googleSecret: <redacted>
  testVmAddress: <redacted>
  logstashHost: <redacted>
---
apiVersion: v1
kind: Secret
metadata:
  namespace: apc
  name: mongo-password
type: Opaque
stringData:
  password: <redacted>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admins-config
  namespace: apc
data:
  admins.txt: |
    <redacted>
  
---
apiVersion: v1
kind: Secret
metadata:
  namespace: apc
  name: https-certs
type: kubernetes.io/tls
stringData:
  tls.crt: |
        -----BEGIN CERTIFICATE-----
        <redacted>
        -----END CERTIFICATE-----
  tls.key: |
        -----BEGIN PRIVATE KEY-----
        <redacted>
        -----END PRIVATE KEY-----
