apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: apc
spec:
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 0.5Gi
    limits:
      cpu: 500m
      memory: 1.5Gi
  rabbitmq:
    additionalConfig: |
      default_user=guest
      default_pass=guest
  persistence:
    storageClassName: standard
    storage: 2Gi
