# Default values for apchelm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

projectName: APC
releaseLabel: 469e7e9ce2799e2a84e34139867a3dc4f08c1391
dockerRepository: apcdevregistry.azurecr.io
websiteHost: apc.l33t.party
testRequestQueue: testInput1
testResultsQueue: testOutput1
LBinternal: 10.0.0.25
environment: dev
